<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>GTALPR</AssemblyName>
    <RootNamespace>FlockSurveillance</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <PackageReference Include="ScriptHookVDotNet3" Version="3.6.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference
        Include="LemonUI.SHVDN3"
        Version="2.2.0"
    />
  </ItemGroup>

  <ItemGroup>
    <None Remove="flock_logo_transparent.png" />
    <None Remove="GTALPR_Logo_Transparent.png" />

    <EmbeddedResource Include="flock_logo_transparent.png">
      <LogicalName>FlockSurveillance.Assets.flock_logo_transparent.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="GTALPR_Logo_Transparent.png">
      <LogicalName>FlockSurveillance.Assets.GTALPR_Logo_Transparent.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
