<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>FlockSurveillance</AssemblyName>
    <RootNamespace>FlockSurveillance</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <PackageReference Include="ScriptHookVDotNet3" Version="3.6.0">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>